import type { Metadata } from "next";
import type { FC, PropsWithChildren } from 'react';

import "./styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en">
      <body>
          <div className="tw-app-layout">{children}</div>
      </body>
  </html>
);

export default RootLayout;
